### ISSUE TITLE
Deploying changes in models

### ISSUE THREAD

**Issue by abhigenie92** [AmmsA/theresumator#28]
I made some changes to the model and want to push it to the deployed heroku website. On running "$ heroku run python manage.py migrate", I get this error:
http://stackoverflow.com/q/28598676/3646408

There I now need to make work on the local before deploying it to heroku. I am getting the following error:
```
$ python2 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 188, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/home/abhishek/.local/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 21, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```

Please suggest.

**Comment by AmmsA** [comment]
If you want to check it out locally, make sure you have your `settings.DATABASES` configured.

In your `settings.py` file, look for the `DATABASES` variable and change it to 


```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

Also, put the `resumator` directory from your [django-resumator repo](https://github.com/abhigenie92/django-resumator/tree/temp_version) in the same working directory where you're executing the `python manage.py migrate`. Do a `python manage.py makemigrations` before, this should change your migration files (which are now not in-synced with the changes you made to the model), see [here](https://github.com/abhigenie92/django-resumator/blob/temp_version/resumator/migrations/0001_initial.py), the fields types are different from what you have in `models.py`.

**Comment by abhigenie92** [comment]
Thanks!!! This works!
